main:default.py
#これは，実験用
#	~/../../Applications/Blender.app/Contents/MacOS/Blender --python default.py -- ${0}.obj
#これは，保存する用
	~/../../Applications/Blender.app/Contents/MacOS/Blender --python saveobj.py -- ${0}.obj -- 1000 -- 10
	~/../../Applications/Blender.app/Contents/MacOS/Blender --python savevol.py -- ${0} -- 1000 -- 10
#	~/../../Applications/Blender.app/Contents/MacOS/Blender --python matome.py -- ${0} -- ${FRAME} --${NUM}
