FRAME=600
RANGE=600
#RANGE=10
main:default.py
#これは，実験用
#	~/../../Applications/Blender.app/Contents/MacOS/Blender --python default.py -- ${0}.obj
##これは，保存する用
#	~/../../Applications/Blender.app/Contents/MacOS/Blender --python saveobj.py -- ${0}.obj -- ${FRAME} -- ${RANGE}
#	~/../../Applications/Blender.app/Contents/MacOS/Blender --python savevol.py -- ${0} -- ${FRAME} -- ${RANGE}
#for make animation
	~/../../Applications/Blender.app/Contents/MacOS/Blender --python makeanim.py -- ${0}.obj -- ${FRAME} -- ${RANGE}

#	~/../../Applications/Blender.app/Contents/MacOS/Blender --python matome.py -- ${0} -- ${FRAME} --${NUM}
